using System.Text.RegularExpressions;

namespace ULinkRPC.CodeGen;

internal static class FacadeEmitter
{
    public static string GenerateClientFacade(
        List<RpcServiceInfo> services,
        string ns,
        string coreRuntimeUsing,
        string clientRuntimeUsing)
    {
        var groups = BuildFacadeGroups(services);
        var callbacks = BuildCallbackBindings(services);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(services),
            "System",
            "System.Threading",
            "System.Threading.Tasks",
            coreRuntimeUsing,
            clientRuntimeUsing);
        var connectionTypeName = NamingHelper.GetClientConnectionTypeName();

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.WriteUsings("System", "System.Threading", "System.Threading.Tasks");
        w.WriteUsings(contractUsings);
        w.Line($"using {clientRuntimeUsing};");
        w.Line($"using {coreRuntimeUsing};");
        w.Line("using ULinkRPC.Client.Unity;");
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock("public sealed class RpcApi");
        w.OpenBlock("public RpcApi(IRpcClient client)");
        w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
        foreach (var group in groups)
            w.Line($"{group.GroupName} = new {GetFacadeGroupTypeName(group.GroupName)}(client);");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
            w.Line($"public {GetFacadeGroupTypeName(group.GroupName)} {group.GroupName} {{ get; }}");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
        {
            var groupTypeName = GetFacadeGroupTypeName(group.GroupName);
            w.OpenBlock($"public sealed class {groupTypeName}");
            w.OpenBlock($"public {groupTypeName}(IRpcClient client)");
            w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
            foreach (var member in group.Members)
                w.Line($"{member.PropertyName} = client.{NamingHelper.GetClientFactoryMethodName(member.Service.InterfaceName)}();");
            w.CloseBlock();
            w.Line();

            foreach (var member in group.Members)
                w.Line($"public {member.Service.InterfaceName} {member.PropertyName} {{ get; }}");
            w.CloseBlock();
            w.Line();
        }

        w.OpenBlock($"public sealed class {connectionTypeName} : IAsyncDisposable");
        w.OpenBlock($"public {connectionTypeName}(RpcClient client)");
        w.Line("Client = client ?? throw new ArgumentNullException(nameof(client));");
        w.Line("Api = new RpcApi(client);");
        w.CloseBlock();
        w.Line();
        w.Line("public RpcApi Api { get; }");
        w.Line("public RpcClient Client { get; }");
        w.Line();

        var connectSignature = callbacks.Count == 0
            ? $"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcClientBuilder builder, CancellationToken ct = default)"
            : $"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcClientBuilder builder, {GetConnectParameterSignature(callbacks)}, CancellationToken ct = default)";
        w.OpenBlock(connectSignature);
        w.Line("if (builder is null) throw new ArgumentNullException(nameof(builder));");
        if (callbacks.Count == 0)
        {
            w.Line($"return builder.ConnectTypedAsync(static client => new {connectionTypeName}(client), configureClient: null, ct);");
        }
        else
        {
            var forwardedArgs = string.Join(", ", callbacks.Select(static binding => binding.ParameterName));
            w.Line($"return builder.ConnectTypedAsync(static client => new {connectionTypeName}(client), client => BindCallbacks(client, {forwardedArgs}), ct);");
        }
        w.CloseBlock();
        w.Line();

        var unityConnectSignature = callbacks.Count == 0
            ? $"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcUnityClientOptions options, CancellationToken ct = default)"
            : $"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcUnityClientOptions options, {GetConnectParameterSignature(callbacks)}, CancellationToken ct = default)";
        w.OpenBlock(unityConnectSignature);
        w.Line("if (options is null) throw new ArgumentNullException(nameof(options));");
        if (callbacks.Count == 0)
        {
            w.Line("return ConnectAsync(options.CreateBuilder(), ct);");
        }
        else
        {
            var forwardedArgs = string.Join(", ", callbacks.Select(static binding => $"{binding.ParameterName}: {binding.ParameterName}"));
            w.Line($"return ConnectAsync(options.CreateBuilder(), {forwardedArgs}, ct);");
        }
        w.CloseBlock();
        w.Line();

        if (callbacks.Count > 0)
        {
            w.OpenBlock($"private static void BindCallbacks(IRpcClient client, {GetBindCallbackSignature(callbacks)})");
            foreach (var callback in callbacks)
            {
                w.OpenBlock($"if ({callback.ParameterName} is not null)");
                w.Line($"{NamingHelper.GetCallbackBinderTypeName(callback.Service.CallbackInterfaceName!)}.Bind(client, {callback.ParameterName});");
                w.CloseBlock();
            }
            w.CloseBlock();
            w.Line();
        }

        w.OpenBlock("public ValueTask DisposeAsync()");
        w.Line("return Client.DisposeAsync();");
        w.CloseBlock();
        w.CloseBlock();
        w.Line();

        w.OpenBlock("public static class RpcApiExtensions");
        w.OpenBlock("public static RpcApi CreateRpcApi(this IRpcClient client)");
        w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
        w.Line("return new RpcApi(client);");
        w.CloseBlock();
        w.CloseBlock();

        w.CloseBlock();
        return w.ToString();
    }

    private static string GetFacadeGroupTypeName(string groupName) => $"{groupName}RpcGroup";

    private static List<FacadeGroupInfo> BuildFacadeGroups(List<RpcServiceInfo> services) =>
        services
            .GroupBy(GetFacadeGroupName)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => new FacadeGroupInfo(g.Key, BuildFacadeMembers(g.ToList())))
            .ToList();

    private static List<FacadeMemberInfo> BuildFacadeMembers(List<RpcServiceInfo> services)
    {
        var members = new List<FacadeMemberInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var svc in services.OrderBy(s => s.InterfaceName, StringComparer.Ordinal))
        {
            var baseName = GetFacadeServicePropertyName(svc.InterfaceName);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }
            members.Add(new FacadeMemberInfo(svc, uniqueName));
        }
        return members;
    }

    private static List<CallbackBindingInfo> BuildCallbackBindings(List<RpcServiceInfo> services)
    {
        var bindings = new List<CallbackBindingInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var service in services
                     .Where(static service => service.HasCallback)
                     .OrderBy(static service => service.CallbackInterfaceName, StringComparer.Ordinal))
        {
            var baseName = NamingHelper.GetCallbackReceiverParamName(service.CallbackInterfaceName!);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }

            bindings.Add(new CallbackBindingInfo(service, uniqueName));
        }

        return bindings;
    }

    private static string GetConnectParameterSignature(List<CallbackBindingInfo> callbacks) =>
        string.Join(", ", callbacks.Select(static callback =>
            $"{callback.Service.CallbackInterfaceName}? {callback.ParameterName} = null"));

    private static string GetBindCallbackSignature(List<CallbackBindingInfo> callbacks) =>
        string.Join(", ", callbacks.Select(static callback =>
            $"{callback.Service.CallbackInterfaceName}? {callback.ParameterName}"));

    private static string GetFacadeGroupName(RpcServiceInfo svc)
    {
        var ns = NamingHelper.GetNamespaceFromFullName(svc.InterfaceFullName);
        if (string.IsNullOrWhiteSpace(ns))
            return "Default";

        var firstSegment = ns.Split('.', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        return NamingHelper.ToPascalIdentifier(firstSegment ?? "Default");
    }

    private static string GetFacadeServicePropertyName(string ifaceName)
    {
        var serviceTypeName = NamingHelper.GetServiceTypeName(ifaceName);
        if (serviceTypeName.EndsWith("Service", StringComparison.Ordinal) &&
            serviceTypeName.Length > "Service".Length)
        {
            serviceTypeName = serviceTypeName[..^"Service".Length];
        }
        return NamingHelper.ToPascalIdentifier(serviceTypeName);
    }

    private sealed class CallbackBindingInfo(RpcServiceInfo service, string parameterName)
    {
        public string ParameterName { get; } = parameterName;
        public RpcServiceInfo Service { get; } = service;
    }
}
