namespace ULinkRPC.CodeGen;

internal static partial class FacadeEmitter
{
    public static string GenerateClientFacade(
        List<RpcServiceInfo> services,
        string ns,
        string coreRuntimeUsing,
        string clientRuntimeUsing)
    {
        var groups = BuildFacadeGroups(services);
        var callbacks = BuildCallbackBindings(services);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(services),
            "System",
            "System.Threading",
            "System.Threading.Tasks",
            coreRuntimeUsing,
            clientRuntimeUsing);
        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.WriteUsings("System", "System.Threading", "System.Threading.Tasks");
        if (callbacks.Count > 0)
            w.WriteUsings("System.Collections.Generic");
        w.WriteUsings(contractUsings);
        w.Line($"using {clientRuntimeUsing};");
        w.Line($"using {coreRuntimeUsing};");
        w.Line();

        w.OpenBlock($"namespace {ns}");

        w.OpenBlock("public sealed class RpcApi");
        w.OpenBlock("public RpcApi(IRpcClient client)");
        w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
        foreach (var group in groups)
            w.Line($"{group.GroupName} = new {GetFacadeGroupTypeName(group.GroupName)}(client);");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
            w.Line($"public {GetFacadeGroupTypeName(group.GroupName)} {group.GroupName} {{ get; }}");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
        {
            var groupTypeName = GetFacadeGroupTypeName(group.GroupName);
            w.OpenBlock($"public sealed class {groupTypeName}");
            w.OpenBlock($"public {groupTypeName}(IRpcClient client)");
            w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
            foreach (var member in group.Members)
                w.Line($"{member.PropertyName} = client.{NamingHelper.GetClientFactoryMethodName(member.Service.InterfaceName)}();");
            w.CloseBlock();
            w.Line();

            foreach (var member in group.Members)
                w.Line($"public {member.Service.InterfaceName} {member.PropertyName} {{ get; }}");
            w.CloseBlock();
            w.Line();
        }

        w.CloseBlock();
        w.Line();

        w.OpenBlock($"namespace {clientRuntimeUsing}");
        w.OpenBlock("public sealed class RpcClient : IAsyncDisposable");
        w.Line("private readonly RpcClientRuntime _runtime;");
        if (callbacks.Count > 0)
            w.Line("private readonly RpcCallbackBindings? _callbacks;");
        w.Line($"private global::{ns}.RpcApi? _api;");
        w.Line();

        w.OpenBlock("public RpcClient(RpcClientOptions options)");
        w.Line("Options = options ?? throw new ArgumentNullException(nameof(options));");
        w.Line("_runtime = new RpcClientRuntime(options.Transport, options.Serializer, options.KeepAlive);");
        w.CloseBlock();
        w.Line();

        if (callbacks.Count > 0)
        {
            w.OpenBlock("public RpcClient(RpcClientOptions options, RpcCallbackBindings callbacks) : this(options)");
            w.Line("_callbacks = callbacks ?? throw new ArgumentNullException(nameof(callbacks));");
            w.CloseBlock();
            w.Line();
            EmitCallbackTypes(w, callbacks, ns);
        }

        w.OpenBlock("public event Action<Exception?>? Disconnected");
        w.Line("add => _runtime.Disconnected += value;");
        w.Line("remove => _runtime.Disconnected -= value;");
        w.CloseBlock();
        w.Line();

        w.Line("public RpcClientOptions Options { get; }");
        w.Line($"public global::{ns}.RpcApi Api => _api ??= new global::{ns}.RpcApi(_runtime);");
        w.Line();

        w.OpenBlock("public ValueTask ConnectAsync(CancellationToken ct = default)");
        if (callbacks.Count > 0)
        {
            w.Line("if (_callbacks is not null)");
            w.Line("    _callbacks.Bind(_runtime);");
        }
        w.Line("return _runtime.StartAsync(ct);");
        w.CloseBlock();
        w.Line();

        w.OpenBlock("public ValueTask DisposeAsync()");
        w.Line("return _runtime.DisposeAsync();");
        w.CloseBlock();

        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    private static string GetFacadeGroupTypeName(string groupName) => $"{groupName}RpcGroup";

    private static List<FacadeGroupInfo> BuildFacadeGroups(List<RpcServiceInfo> services) =>
        services
            .GroupBy(GetFacadeGroupName)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => new FacadeGroupInfo(g.Key, BuildFacadeMembers(g.ToList())))
            .ToList();

    private static List<FacadeMemberInfo> BuildFacadeMembers(List<RpcServiceInfo> services)
    {
        var members = new List<FacadeMemberInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var svc in services.OrderBy(s => s.InterfaceName, StringComparer.Ordinal))
        {
            var baseName = GetFacadeServicePropertyName(svc.InterfaceName);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }
            members.Add(new FacadeMemberInfo(svc, uniqueName));
        }
        return members;
    }

    private static List<CallbackBindingInfo> BuildCallbackBindings(List<RpcServiceInfo> services)
    {
        var bindings = new List<CallbackBindingInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var service in services
                     .Where(static service => service.HasCallback)
                     .OrderBy(static service => service.CallbackInterfaceName, StringComparer.Ordinal))
        {
            var baseName = NamingHelper.GetCallbackReceiverParamName(service.CallbackInterfaceName!);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }

            bindings.Add(new CallbackBindingInfo(service, uniqueName));
        }

        return bindings;
    }

    private static string GetFacadeGroupName(RpcServiceInfo svc)
    {
        var ns = NamingHelper.GetNamespaceFromFullName(svc.InterfaceFullName);
        if (string.IsNullOrWhiteSpace(ns))
            return "Default";

        var firstSegment = ns.Split('.', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        return NamingHelper.ToPascalIdentifier(firstSegment ?? "Default");
    }

    private static string GetFacadeServicePropertyName(string ifaceName)
    {
        var serviceTypeName = NamingHelper.GetServiceTypeName(ifaceName);
        if (serviceTypeName.EndsWith("Service", StringComparison.Ordinal) &&
            serviceTypeName.Length > "Service".Length)
        {
            serviceTypeName = serviceTypeName[..^"Service".Length];
        }
        return NamingHelper.ToPascalIdentifier(serviceTypeName);
    }

    private static string GetCallbackMethodParameterSignature(List<RpcParameterInfo> parameters) =>
        string.Join(", ", parameters.Select(static parameter => $"{parameter.TypeName} {parameter.Name}"));

    private static string GetCallbackBaseTypeName(string callbackInterfaceName) =>
        $"{NamingHelper.GetServiceTypeName(callbackInterfaceName)}Base";

    private static string GetCallbackFieldName(string callbackInterfaceName) =>
        "_" + NamingHelper.GetCallbackReceiverParamName(callbackInterfaceName);

    private sealed class CallbackBindingInfo(RpcServiceInfo service, string parameterName)
    {
        public string ParameterName { get; } = parameterName;
        public RpcServiceInfo Service { get; } = service;
    }
}
