using System.Text.RegularExpressions;

namespace ULinkRPC.CodeGen;

internal static class FacadeEmitter
{
    public static string GenerateClientFacade(
        List<RpcServiceInfo> services,
        string ns,
        string coreRuntimeUsing,
        string clientRuntimeUsing)
    {
        var groups = BuildFacadeGroups(services);
        var callbacks = BuildCallbackBindings(services);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(services),
            "System",
            "System.Threading",
            "System.Threading.Tasks",
            coreRuntimeUsing,
            clientRuntimeUsing);
        var connectionTypeName = NamingHelper.GetClientConnectionTypeName();
        var typedClientName = GetTypedClientHostName(groups);
        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.WriteUsings("System", "System.Threading", "System.Threading.Tasks");
        if (callbacks.Count > 0)
            w.WriteUsings("System.Collections", "System.Collections.Generic");
        w.WriteUsings(contractUsings);
        w.Line($"using {clientRuntimeUsing};");
        w.Line($"using {coreRuntimeUsing};");
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock("public sealed class RpcApi");
        w.OpenBlock("public RpcApi(IRpcClient client)");
        w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
        foreach (var group in groups)
            w.Line($"{group.GroupName} = new {GetFacadeGroupTypeName(group.GroupName)}(client);");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
            w.Line($"public {GetFacadeGroupTypeName(group.GroupName)} {group.GroupName} {{ get; }}");
        w.CloseBlock();
        w.Line();

        foreach (var group in groups)
        {
            var groupTypeName = GetFacadeGroupTypeName(group.GroupName);
            w.OpenBlock($"public sealed class {groupTypeName}");
            w.OpenBlock($"public {groupTypeName}(IRpcClient client)");
            w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
            foreach (var member in group.Members)
                w.Line($"{member.PropertyName} = client.{NamingHelper.GetClientFactoryMethodName(member.Service.InterfaceName)}();");
            w.CloseBlock();
            w.Line();

            foreach (var member in group.Members)
                w.Line($"public {member.Service.InterfaceName} {member.PropertyName} {{ get; }}");
            w.CloseBlock();
            w.Line();
        }

        w.OpenBlock($"public sealed class {connectionTypeName} : IAsyncDisposable");
        w.OpenBlock($"public {connectionTypeName}(RpcClient client)");
        w.Line("Client = client ?? throw new ArgumentNullException(nameof(client));");
        w.Line("Api = new RpcApi(client);");
        w.CloseBlock();
        w.Line();
        w.Line("public RpcApi Api { get; }");
        w.Line("public RpcClient Client { get; }");
        w.Line();

        w.OpenBlock($"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcClientBuilder builder, CancellationToken ct = default)");
        w.Line("if (builder is null) throw new ArgumentNullException(nameof(builder));");
        w.Line($"return builder.ConnectTypedAsync(static client => new {connectionTypeName}(client), configureClient: null, ct);");
        w.CloseBlock();
        w.Line();

        if (callbacks.Count > 0)
        {
            w.OpenBlock($"public static ValueTask<{connectionTypeName}> ConnectAsync(RpcClientBuilder builder, RpcCallbackBindings callbacks, CancellationToken ct = default)");
            w.Line("if (builder is null) throw new ArgumentNullException(nameof(builder));");
            w.Line("if (callbacks is null) throw new ArgumentNullException(nameof(callbacks));");
            w.Line($"return builder.ConnectTypedAsync(static client => new {connectionTypeName}(client), callbacks.Bind, ct);");
            w.CloseBlock();
            w.Line();

            w.OpenBlock("public sealed class RpcCallbackBindings : IEnumerable<object>");
            foreach (var callback in callbacks)
            {
                var callbackType = callback.Service.CallbackInterfaceName!;
                var callbackField = GetCallbackFieldName(callbackType);
                var receiverName = NamingHelper.GetCallbackReceiverParamName(callbackType);
                w.Line($"private {callbackType}? {callbackField};");
                w.OpenBlock($"public void Add({callbackType} {receiverName})");
                w.Line($"if ({receiverName} is null) throw new ArgumentNullException(nameof({receiverName}));");
                w.OpenBlock($"if ({callbackField} is not null)");
                w.Line($"throw new InvalidOperationException(\"Callback receiver for '{callbackType}' is already registered.\");");
                w.CloseBlock();
                w.Line($"{callbackField} = {receiverName};");
                w.CloseBlock();
                w.Line();
            }
            w.OpenBlock("internal void Bind(IRpcClient client)");
            w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
            foreach (var callback in callbacks)
            {
                var callbackType = callback.Service.CallbackInterfaceName!;
                var callbackField = GetCallbackFieldName(callbackType);
                w.OpenBlock($"if ({callbackField} is not null)");
                w.Line($"{NamingHelper.GetCallbackBinderTypeName(callbackType)}.Bind(client, {callbackField});");
                w.CloseBlock();
            }
            w.CloseBlock();
            w.Line();
            w.OpenBlock("public IEnumerator<object> GetEnumerator()");
            w.Line("yield break;");
            w.CloseBlock();
            w.Line();
            w.OpenBlock("IEnumerator IEnumerable.GetEnumerator()");
            w.Line("return GetEnumerator();");
            w.CloseBlock();
            w.Line();
            w.CloseBlock();
            w.Line();

            foreach (var callback in callbacks)
            {
                var callbackType = callback.Service.CallbackInterfaceName!;
                w.OpenBlock($"public abstract class {GetCallbackBaseTypeName(callbackType)} : {callbackType}");
                foreach (var method in callback.Service.CallbackMethods.OrderBy(static method => method.MethodId))
                {
                    w.Line();
                    w.OpenBlock($"public virtual void {method.Name}({GetCallbackMethodParameterSignature(method.Parameters)})");
                    w.CloseBlock();
                }
                w.CloseBlock();
                w.Line();
            }
        }

        w.OpenBlock("public ValueTask DisposeAsync()");
        w.Line("return Client.DisposeAsync();");
        w.CloseBlock();
        w.CloseBlock();
        w.Line();

        w.OpenBlock("public static class RpcApiExtensions");
        w.OpenBlock("public static RpcApi CreateRpcApi(this IRpcClient client)");
        w.Line("if (client is null) throw new ArgumentNullException(nameof(client));");
        w.Line("return new RpcApi(client);");
        w.CloseBlock();
        w.CloseBlock();
        w.Line();

        w.OpenBlock($"public sealed class {typedClientName} : IAsyncDisposable");
        w.OpenBlock($"private {typedClientName}({connectionTypeName} connection)");
        w.Line("Connection = connection ?? throw new ArgumentNullException(nameof(connection));");
        w.CloseBlock();
        w.Line();
        w.Line($"public {connectionTypeName} Connection {{ get; }}");
        w.Line("public RpcApi Api => Connection.Api;");
        w.Line("public RpcClient Client => Connection.Client;");
        foreach (var group in groups)
            w.Line($"public {GetFacadeGroupTypeName(group.GroupName)} {group.GroupName} => Api.{group.GroupName};");
        w.Line();
        w.OpenBlock($"public static async ValueTask<{typedClientName}> ConnectAsync(RpcClientBuilder builder, CancellationToken ct = default)");
        w.Line($"var connection = await {connectionTypeName}.ConnectAsync(builder, ct);");
        w.Line($"return new {typedClientName}(connection);");
        w.CloseBlock();
        w.Line();
        if (callbacks.Count > 0)
        {
            w.OpenBlock($"public static async ValueTask<{typedClientName}> ConnectAsync(RpcClientBuilder builder, {connectionTypeName}.RpcCallbackBindings callbacks, CancellationToken ct = default)");
            w.Line($"var connection = await {connectionTypeName}.ConnectAsync(builder, callbacks, ct);");
            w.Line($"return new {typedClientName}(connection);");
            w.CloseBlock();
            w.Line();
        }
        w.OpenBlock("public ValueTask DisposeAsync()");
        w.Line("return Connection.DisposeAsync();");
        w.CloseBlock();
        w.CloseBlock();

        w.CloseBlock();
        return w.ToString();
    }

    private static string GetFacadeGroupTypeName(string groupName) => $"{groupName}RpcGroup";

    private static string GetTypedClientHostName(List<FacadeGroupInfo> groups)
    {
        if (groups.Count == 1 && !string.Equals(groups[0].GroupName, "Default", StringComparison.Ordinal))
            return $"{groups[0].GroupName}RpcClient";

        return "RpcClientHost";
    }

    private static List<FacadeGroupInfo> BuildFacadeGroups(List<RpcServiceInfo> services) =>
        services
            .GroupBy(GetFacadeGroupName)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => new FacadeGroupInfo(g.Key, BuildFacadeMembers(g.ToList())))
            .ToList();

    private static List<FacadeMemberInfo> BuildFacadeMembers(List<RpcServiceInfo> services)
    {
        var members = new List<FacadeMemberInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var svc in services.OrderBy(s => s.InterfaceName, StringComparer.Ordinal))
        {
            var baseName = GetFacadeServicePropertyName(svc.InterfaceName);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }
            members.Add(new FacadeMemberInfo(svc, uniqueName));
        }
        return members;
    }

    private static List<CallbackBindingInfo> BuildCallbackBindings(List<RpcServiceInfo> services)
    {
        var bindings = new List<CallbackBindingInfo>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var service in services
                     .Where(static service => service.HasCallback)
                     .OrderBy(static service => service.CallbackInterfaceName, StringComparer.Ordinal))
        {
            var baseName = NamingHelper.GetCallbackReceiverParamName(service.CallbackInterfaceName!);
            var uniqueName = baseName;
            var suffix = 2;
            while (!usedNames.Add(uniqueName))
            {
                uniqueName = $"{baseName}{suffix}";
                suffix++;
            }

            bindings.Add(new CallbackBindingInfo(service, uniqueName));
        }

        return bindings;
    }

    private static string GetFacadeGroupName(RpcServiceInfo svc)
    {
        var ns = NamingHelper.GetNamespaceFromFullName(svc.InterfaceFullName);
        if (string.IsNullOrWhiteSpace(ns))
            return "Default";

        var firstSegment = ns.Split('.', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        return NamingHelper.ToPascalIdentifier(firstSegment ?? "Default");
    }

    private static string GetFacadeServicePropertyName(string ifaceName)
    {
        var serviceTypeName = NamingHelper.GetServiceTypeName(ifaceName);
        if (serviceTypeName.EndsWith("Service", StringComparison.Ordinal) &&
            serviceTypeName.Length > "Service".Length)
        {
            serviceTypeName = serviceTypeName[..^"Service".Length];
        }
        return NamingHelper.ToPascalIdentifier(serviceTypeName);
    }

    private static string GetCallbackMethodParameterSignature(List<RpcParameterInfo> parameters) =>
        string.Join(", ", parameters.Select(static parameter => $"{parameter.TypeName} {parameter.Name}"));

    private static string GetCallbackBaseTypeName(string callbackInterfaceName) =>
        $"{NamingHelper.GetServiceTypeName(callbackInterfaceName)}Base";

    private static string GetCallbackFieldName(string callbackInterfaceName) =>
        "_" + NamingHelper.GetCallbackReceiverParamName(callbackInterfaceName);

    private sealed class CallbackBindingInfo(RpcServiceInfo service, string parameterName)
    {
        public string ParameterName { get; } = parameterName;
        public RpcServiceInfo Service { get; } = service;
    }
}
