namespace ULinkRPC.CodeGen;

internal static partial class ServerEmitter
{
    public static string GenerateCallbackProxy(
        RpcServiceInfo svc, string ns, string coreRuntimeUsing, string serverRuntimeUsing)
    {
        var cbName = svc.CallbackInterfaceName!;
        var proxyTypeName = NamingHelper.GetCallbackProxyTypeName(cbName);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(svc),
            "System", coreRuntimeUsing, serverRuntimeUsing);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.Line("using System;");
        w.WriteUsings(contractUsings);
        w.WriteUsings(coreRuntimeUsing, serverRuntimeUsing);
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock($"public sealed class {proxyTypeName} : {cbName}");
        w.Line($"private const int ServiceId = {svc.ServiceId};");
        w.Line("private readonly RpcSession _session;");
        w.Line();
        w.Line($"public {proxyTypeName}(RpcSession session) {{ _session = session; }}");
        w.Line();

        foreach (var m in svc.CallbackMethods)
        {
            var paramSig = NamingHelper.GetMethodParameterSignature(m.Parameters);
            var argType = NamingHelper.GetCallbackPayloadType(m);
            var argVal = NamingHelper.GetCallbackPayloadValue(m);

            w.OpenBlock($"public void {m.Name}({paramSig})");
            w.Line($"_ = _session.PushAsync<{argType}>(ServiceId, {m.MethodId}, {argVal}).AsTask();");
            w.CloseBlock();
            w.Line();
        }

        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    private static void EmitCallbackFactoryBindOverload(CodeWriter w, RpcServiceInfo svc)
    {
        var callbackInterfaceName = svc.CallbackInterfaceName!;
        var callbackProxyTypeName = NamingHelper.GetCallbackProxyTypeName(callbackInterfaceName);

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry, Func<{callbackInterfaceName}, {svc.InterfaceName}> implFactory)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (implFactory is null) throw new ArgumentNullException(nameof(implFactory));");
        w.Line($"BindFactory(registry, session => implFactory(new {callbackProxyTypeName}(session)) ?? throw new InvalidOperationException(\"Service implementation factory returned null.\"));");
        w.CloseBlock();
        w.Line();
    }
}
