namespace ULinkRPC.CodeGen;

internal static partial class ServerEmitter
{
    public static string GenerateBinder(
        RpcServiceInfo svc, string ns, string coreRuntimeUsing, string serverRuntimeUsing)
    {
        var ifaceName = svc.InterfaceName;
        var binderTypeName = NamingHelper.GetBinderTypeName(ifaceName);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(svc),
            "System", "System.Threading.Tasks", coreRuntimeUsing, serverRuntimeUsing);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.WriteUsings("System", "System.Threading.Tasks");
        w.WriteUsings(contractUsings);
        w.WriteUsings(coreRuntimeUsing, serverRuntimeUsing);
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock($"public static class {binderTypeName}");
        w.Line($"private const int ServiceId = {svc.ServiceId};");
        w.Line();

        EmitDelegateBindOverload(w, svc);
        if (svc.HasCallback)
            EmitCallbackFactoryBindOverload(w, svc);

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry, {ifaceName} impl)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (impl is null) throw new ArgumentNullException(nameof(impl));");
        w.Line("BindFactory(registry, _ => impl);");
        w.CloseBlock();
        w.Line();

        w.OpenBlock($"public static void BindFactory(RpcServiceRegistry registry, Func<RpcSession, {ifaceName}> implFactory)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (implFactory is null) throw new ArgumentNullException(nameof(implFactory));");

        foreach (var m in svc.Methods)
        {
            var argType = NamingHelper.GetRequestPayloadType(m);
            w.OpenBlock($"registry.Register(ServiceId, {m.MethodId}, async (server, req, ct) =>");
            w.Line($"var impl = server.GetOrAddScopedService(ServiceId, implFactory);");
            w.Line($"var arg = server.Serializer.Deserialize<{argType}>(req.Payload.AsSpan())!;");
            if (m.IsVoid)
            {
                w.Line($"await impl.{m.Name}(arg);");
                w.Line("return new RpcResponseEnvelope { RequestId = req.RequestId, Status = RpcStatus.Ok, Payload = Array.Empty<byte>() };");
            }
            else
            {
                w.Line($"var resp = await impl.{m.Name}(arg);");
                w.Line("return new RpcResponseEnvelope { RequestId = req.RequestId, Status = RpcStatus.Ok, Payload = server.Serializer.Serialize(resp) };");
            }

            w.CloseBlock(");");
            w.Line();
        }

        w.CloseBlock();
        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    private static void EmitDelegateBindOverload(CodeWriter w, RpcServiceInfo svc)
    {
        var delegateParams = svc.Methods
            .Select(m => $"{NamingHelper.GetDelegateType(m)} {NamingHelper.GetHandlerParameterName(m.Name)}")
            .ToList();
        var paramList = delegateParams.Count > 0
            ? ", " + string.Join(", ", delegateParams)
            : "";
        var ctorArgs = string.Join(", ",
            svc.Methods.Select(m => NamingHelper.GetHandlerParameterName(m.Name)));

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry{paramList})");
        w.Line($"BindFactory(registry, _ => new DelegateImpl({ctorArgs}));");
        w.CloseBlock();
        w.Line();

        w.OpenBlock($"private sealed class DelegateImpl : {svc.InterfaceName}");

        foreach (var method in svc.Methods)
            w.Line($"private readonly {NamingHelper.GetDelegateType(method)} {NamingHelper.GetHandlerFieldName(method.Name)};");

        if (svc.Methods.Count > 0) w.Line();

        var ctorParams = string.Join(", ",
            svc.Methods.Select(m => $"{NamingHelper.GetDelegateType(m)} {NamingHelper.GetHandlerParameterName(m.Name)}"));
        w.OpenBlock($"public DelegateImpl({ctorParams})");
        foreach (var method in svc.Methods)
        {
            var handlerParam = NamingHelper.GetHandlerParameterName(method.Name);
            var handlerField = NamingHelper.GetHandlerFieldName(method.Name);
            w.Line($"{handlerField} = {handlerParam} ?? throw new ArgumentNullException(nameof({handlerParam}));");
        }
        w.CloseBlock();
        w.Line();

        foreach (var method in svc.Methods)
        {
            var paramSig = NamingHelper.GetMethodParameterSignature(method.Parameters);
            var returnType = NamingHelper.GetInterfaceReturnType(method);
            var invokeArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
            var fieldName = NamingHelper.GetHandlerFieldName(method.Name);

            w.OpenBlock($"public {returnType} {method.Name}({paramSig})");
            w.Line($"return {fieldName}({invokeArgs});");
            w.CloseBlock();
            w.Line();
        }

        w.CloseBlock();
        w.Line();
    }

}
