namespace ULinkRPC.CodeGen;

internal static class ServerEmitter
{
    public static string GenerateBinder(
        RpcServiceInfo svc, string ns, string coreRuntimeUsing, string serverRuntimeUsing)
    {
        var ifaceName = svc.InterfaceName;
        var binderTypeName = NamingHelper.GetBinderTypeName(ifaceName);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(svc),
            "System", "System.Threading.Tasks", coreRuntimeUsing, serverRuntimeUsing);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.WriteUsings("System", "System.Threading.Tasks");
        w.WriteUsings(contractUsings);
        w.WriteUsings(coreRuntimeUsing, serverRuntimeUsing);
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock($"public static class {binderTypeName}");
        w.Line($"private const int ServiceId = {svc.ServiceId};");
        w.Line();

        EmitDelegateBindOverload(w, svc);
        if (svc.HasCallback)
            EmitCallbackFactoryBindOverload(w, svc);

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry, {ifaceName} impl)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (impl is null) throw new ArgumentNullException(nameof(impl));");
        w.Line("BindFactory(registry, _ => impl);");
        w.CloseBlock();
        w.Line();

        w.OpenBlock($"public static void BindFactory(RpcServiceRegistry registry, Func<RpcSession, {ifaceName}> implFactory)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (implFactory is null) throw new ArgumentNullException(nameof(implFactory));");

        foreach (var m in svc.Methods)
        {
            var argType = NamingHelper.GetRequestPayloadType(m);
            w.OpenBlock($"registry.Register(ServiceId, {m.MethodId}, async (server, req, ct) =>");
            w.Line($"var impl = server.GetOrAddScopedService(ServiceId, implFactory);");

            if (m.Parameters.Count == 1)
            {
                w.Line($"var arg1 = server.Serializer.Deserialize<{argType}>(req.Payload.AsSpan())!;");
            }
            else if (m.Parameters.Count > 1)
            {
                var deconstructVars = NamingHelper.GetDeconstructVariableList(m.Parameters.Count);
                w.Line($"var ({deconstructVars}) = server.Serializer.Deserialize<{argType}>(req.Payload.AsSpan())!;");
            }

            var invokeArgs = NamingHelper.GetInvokeArguments(m.Parameters.Count);
            if (m.IsVoid)
            {
                w.Line($"await impl.{m.Name}({invokeArgs});");
                w.Line("return new RpcResponseEnvelope { RequestId = req.RequestId, Status = RpcStatus.Ok, Payload = Array.Empty<byte>() };");
            }
            else
            {
                w.Line($"var resp = await impl.{m.Name}({invokeArgs});");
                w.Line("return new RpcResponseEnvelope { RequestId = req.RequestId, Status = RpcStatus.Ok, Payload = server.Serializer.Serialize(resp) };");
            }

            w.CloseBlock(");");
            w.Line();
        }

        w.CloseBlock();
        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    public static string GenerateAllServicesBinder(
        List<RpcServiceInfo> services, string ns, string runtimeUsing)
    {
        var requiresReflectionHelpers = services.Count > 0;
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(services),
            requiresReflectionHelpers
                ? ["System", "System.Linq", "System.Reflection", runtimeUsing]
                : [runtimeUsing]);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        if (requiresReflectionHelpers)
        {
            w.Line("using System;");
            w.Line("using System.Linq;");
            w.Line("using System.Reflection;");
        }
        w.WriteUsings(contractUsings);
        w.Line($"using {runtimeUsing};");
        w.Line();
        w.OpenBlock($"namespace {ns}");
        w.OpenBlock("public static class AllServicesBinder");

        w.OpenBlock("public static void BindAll(RpcServiceRegistry registry)");
        foreach (var svc in services)
        {
            var binderTypeName = NamingHelper.GetBinderTypeName(svc.InterfaceName);
            if (svc.HasCallback)
                w.Line($"{binderTypeName}.Bind(registry, CreateCallbackServiceFactory<{svc.InterfaceName}, {svc.CallbackInterfaceName}>());");
            else
                w.Line($"{binderTypeName}.BindFactory(registry, CreateServiceFactory<{svc.InterfaceName}>());");
        }
        w.CloseBlock();
        w.Line();

        var paramList = string.Join("",
            services.Select(s =>
            {
                if (!s.HasCallback)
                    return $", {s.InterfaceName} {NamingHelper.GetServiceParamName(s.InterfaceName)}";

                var factoryParamName = NamingHelper.GetServiceFactoryParamName(s.InterfaceName);
                return $", Func<{s.CallbackInterfaceName}, {s.InterfaceName}> {factoryParamName}";
            }));
        w.OpenBlock($"public static void BindAll(RpcServiceRegistry registry{paramList})");

        foreach (var svc in services)
        {
            var binderTypeName = NamingHelper.GetBinderTypeName(svc.InterfaceName);
            var paramName = svc.HasCallback
                ? NamingHelper.GetServiceFactoryParamName(svc.InterfaceName)
                : NamingHelper.GetServiceParamName(svc.InterfaceName);
            w.Line($"{binderTypeName}.Bind(registry, {paramName});");
        }

        w.CloseBlock();

        if (requiresReflectionHelpers)
        {
            w.Line();
            EmitReflectionHelpers(w);
        }

        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    public static string GenerateCallbackProxy(
        RpcServiceInfo svc, string ns, string coreRuntimeUsing, string serverRuntimeUsing)
    {
        var cbName = svc.CallbackInterfaceName!;
        var proxyTypeName = NamingHelper.GetCallbackProxyTypeName(cbName);
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(svc),
            "System", coreRuntimeUsing, serverRuntimeUsing);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        w.Line("using System;");
        w.WriteUsings(contractUsings);
        w.WriteUsings(coreRuntimeUsing, serverRuntimeUsing);
        w.Line();
        w.OpenBlock($"namespace {ns}");

        w.OpenBlock($"public sealed class {proxyTypeName} : {cbName}");
        w.Line($"private const int ServiceId = {svc.ServiceId};");
        w.Line("private readonly RpcSession _session;");
        w.Line();
        w.Line($"public {proxyTypeName}(RpcSession session) {{ _session = session; }}");
        w.Line();

        foreach (var m in svc.CallbackMethods)
        {
            var paramSig = NamingHelper.GetMethodParameterSignature(m.Parameters);
            var argType = NamingHelper.GetCallbackPayloadType(m);
            var argVal = NamingHelper.GetCallbackPayloadValue(m);

            w.OpenBlock($"public void {m.Name}({paramSig})");
            w.Line($"_ = _session.PushAsync<{argType}>(ServiceId, {m.MethodId}, {argVal}).AsTask();");
            w.CloseBlock();
            w.Line();
        }

        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    private static void EmitDelegateBindOverload(CodeWriter w, RpcServiceInfo svc)
    {
        var delegateParams = svc.Methods
            .Select(m => $"{NamingHelper.GetDelegateType(m)} {NamingHelper.GetHandlerParameterName(m.Name)}")
            .ToList();
        var paramList = delegateParams.Count > 0
            ? ", " + string.Join(", ", delegateParams)
            : "";
        var ctorArgs = string.Join(", ",
            svc.Methods.Select(m => NamingHelper.GetHandlerParameterName(m.Name)));

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry{paramList})");
        w.Line($"BindFactory(registry, _ => new DelegateImpl({ctorArgs}));");
        w.CloseBlock();
        w.Line();

        w.OpenBlock($"private sealed class DelegateImpl : {svc.InterfaceName}");

        foreach (var method in svc.Methods)
            w.Line($"private readonly {NamingHelper.GetDelegateType(method)} {NamingHelper.GetHandlerFieldName(method.Name)};");

        if (svc.Methods.Count > 0) w.Line();

        var ctorParams = string.Join(", ",
            svc.Methods.Select(m => $"{NamingHelper.GetDelegateType(m)} {NamingHelper.GetHandlerParameterName(m.Name)}"));
        w.OpenBlock($"public DelegateImpl({ctorParams})");
        foreach (var method in svc.Methods)
        {
            var handlerParam = NamingHelper.GetHandlerParameterName(method.Name);
            var handlerField = NamingHelper.GetHandlerFieldName(method.Name);
            w.Line($"{handlerField} = {handlerParam} ?? throw new ArgumentNullException(nameof({handlerParam}));");
        }
        w.CloseBlock();
        w.Line();

        foreach (var method in svc.Methods)
        {
            var paramSig = NamingHelper.GetMethodParameterSignature(method.Parameters);
            var returnType = NamingHelper.GetInterfaceReturnType(method);
            var invokeArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
            var fieldName = NamingHelper.GetHandlerFieldName(method.Name);

            w.OpenBlock($"public {returnType} {method.Name}({paramSig})");
            w.Line($"return {fieldName}({invokeArgs});");
            w.CloseBlock();
            w.Line();
        }

        w.CloseBlock();
        w.Line();
    }

    private static void EmitCallbackFactoryBindOverload(CodeWriter w, RpcServiceInfo svc)
    {
        var callbackInterfaceName = svc.CallbackInterfaceName!;
        var callbackProxyTypeName = NamingHelper.GetCallbackProxyTypeName(callbackInterfaceName);

        w.OpenBlock($"public static void Bind(RpcServiceRegistry registry, Func<{callbackInterfaceName}, {svc.InterfaceName}> implFactory)");
        w.Line("if (registry is null) throw new ArgumentNullException(nameof(registry));");
        w.Line("if (implFactory is null) throw new ArgumentNullException(nameof(implFactory));");
        w.Line($"BindFactory(registry, session => implFactory(new {callbackProxyTypeName}(session)) ?? throw new InvalidOperationException(\"Service implementation factory returned null.\"));");
        w.CloseBlock();
        w.Line();
    }

    private static void EmitReflectionHelpers(CodeWriter w)
    {
        w.OpenBlock("private static Func<RpcSession, TService> CreateServiceFactory<TService>()");
        w.Line("var implType = ResolveImplementationType(typeof(TService));");
        w.Line("var ctor = implType.GetConstructor(Type.EmptyTypes);");
        w.OpenBlock("if (ctor is null)");
        w.Line("throw new InvalidOperationException($\"No public parameterless constructor found for service implementation '{implType.FullName}'.\");");
        w.CloseBlock();
        w.Line("return _ => (TService)ctor.Invoke(Array.Empty<object?>());");
        w.CloseBlock();
        w.Line();

        w.OpenBlock("private static Func<TCallback, TService> CreateCallbackServiceFactory<TService, TCallback>()");
        w.Line("var implType = ResolveImplementationType(typeof(TService));");
        w.Line("var callbackType = typeof(TCallback);");
        w.Line("var callbackCtor = implType.GetConstructors(BindingFlags.Public | BindingFlags.Instance)");
        w.Line("    .SingleOrDefault(static ctor =>");
        w.Line("    {");
        w.Line("        var parameters = ctor.GetParameters();");
        w.Line("        return parameters.Length == 1 && parameters[0].ParameterType.IsAssignableFrom(typeof(TCallback));");
        w.Line("    });");
        w.OpenBlock("if (callbackCtor is not null)");
        w.Line("return callback => (TService)callbackCtor.Invoke([callback!]);");
        w.CloseBlock();
        w.Line();
        w.Line("var defaultCtor = implType.GetConstructor(Type.EmptyTypes);");
        w.OpenBlock("if (defaultCtor is not null)");
        w.Line("return _ => (TService)defaultCtor.Invoke(Array.Empty<object?>());");
        w.CloseBlock();
        w.Line();
        w.Line("throw new InvalidOperationException($\"No suitable public constructor found for service implementation '{implType.FullName}'. Expected either a parameterless constructor or one accepting '{callbackType.FullName}'.\");");
        w.CloseBlock();
        w.Line();

        w.OpenBlock("private static Type ResolveImplementationType(Type serviceType)");
        w.Line("var implementations = typeof(AllServicesBinder).Assembly.GetTypes()");
        w.Line("    .Where(type => !type.IsAbstract && !type.IsInterface && !type.IsNested && serviceType.IsAssignableFrom(type))");
        w.Line("    .ToArray();");
        w.OpenBlock("if (implementations.Length == 1)");
        w.Line("return implementations[0];");
        w.CloseBlock();
        w.OpenBlock("if (implementations.Length == 0)");
        w.Line("throw new InvalidOperationException($\"No service implementation found for '{serviceType.FullName}' in assembly '{typeof(AllServicesBinder).Assembly.GetName().Name}'.\");");
        w.CloseBlock();
        w.Line("var names = string.Join(\", \", implementations.Select(static type => type.FullName));");
        w.Line("throw new InvalidOperationException($\"Multiple service implementations found for '{serviceType.FullName}': {names}. Use the BindAll overload that accepts explicit service instances or factories instead.\");");
        w.CloseBlock();
    }
}
