namespace ULinkRPC.CodeGen;

internal static partial class ServerEmitter
{
    public static string GenerateAllServicesBinder(
        List<RpcServiceInfo> services, string ns, string runtimeUsing)
    {
        var requiresReflectionHelpers = services.Count > 0;
        var contractUsings = NamingHelper.ExcludeUsingDirectives(
            NamingHelper.GetContractUsingDirectives(services),
            requiresReflectionHelpers
                ? ["System", "System.Linq", "System.Reflection", runtimeUsing]
                : [runtimeUsing]);

        var w = new CodeWriter();
        w.WriteAutoGeneratedHeader();
        if (requiresReflectionHelpers)
        {
            w.Line("using System;");
            w.Line("using System.Linq;");
            w.Line("using System.Reflection;");
        }
        w.WriteUsings(contractUsings);
        w.Line($"using {runtimeUsing};");
        w.Line();
        w.Line($"[assembly: RpcGeneratedServicesBinder(typeof({ns}.AllServicesBinder))]");
        w.Line();
        w.OpenBlock($"namespace {ns}");
        w.OpenBlock("public static class AllServicesBinder");

        EmitAutomaticBindAllOverload(w, services);

        if (requiresReflectionHelpers)
        {
            w.Line();
            EmitReflectionHelpers(w);
        }

        w.CloseBlock();
        w.CloseBlock();
        return w.ToString();
    }

    private static void EmitAutomaticBindAllOverload(CodeWriter w, List<RpcServiceInfo> services)
    {
        w.OpenBlock("public static void BindAll(RpcServiceRegistry registry)");
        foreach (var service in services)
        {
            var binderTypeName = NamingHelper.GetBinderTypeName(service.InterfaceName);
            if (service.HasCallback)
                w.Line($"{binderTypeName}.Bind(registry, CreateCallbackServiceFactory<{service.InterfaceName}, {service.CallbackInterfaceName}>());");
            else
                w.Line($"{binderTypeName}.BindFactory(registry, CreateServiceFactory<{service.InterfaceName}>());");
        }
        w.CloseBlock();
    }

    private static void EmitReflectionHelpers(CodeWriter w)
    {
        w.OpenBlock("private static Func<RpcSession, TService> CreateServiceFactory<TService>()");
        w.Line("var implType = ResolveImplementationType(typeof(TService));");
        w.Line("var ctor = implType.GetConstructor(Type.EmptyTypes);");
        w.OpenBlock("if (ctor is null)");
        w.Line("throw new InvalidOperationException($\"No public parameterless constructor found for service implementation '{implType.FullName}'.\");");
        w.CloseBlock();
        w.Line("return _ => (TService)ctor.Invoke(Array.Empty<object?>());");
        w.CloseBlock();
        w.Line();

        w.OpenBlock("private static Func<TCallback, TService> CreateCallbackServiceFactory<TService, TCallback>()");
        w.Line("var implType = ResolveImplementationType(typeof(TService));");
        w.Line("var callbackType = typeof(TCallback);");
        w.Line("var callbackCtor = implType.GetConstructors(BindingFlags.Public | BindingFlags.Instance)");
        w.Line("    .SingleOrDefault(static ctor =>");
        w.Line("    {");
        w.Line("        var parameters = ctor.GetParameters();");
        w.Line("        return parameters.Length == 1 && parameters[0].ParameterType.IsAssignableFrom(typeof(TCallback));");
        w.Line("    });");
        w.OpenBlock("if (callbackCtor is not null)");
        w.Line("return callback => (TService)callbackCtor.Invoke([callback!]);");
        w.CloseBlock();
        w.Line();
        w.Line("var defaultCtor = implType.GetConstructor(Type.EmptyTypes);");
        w.OpenBlock("if (defaultCtor is not null)");
        w.Line("return _ => (TService)defaultCtor.Invoke(Array.Empty<object?>());");
        w.CloseBlock();
        w.Line();
        w.Line("throw new InvalidOperationException($\"No suitable public constructor found for service implementation '{implType.FullName}'. Expected either a parameterless constructor or one accepting '{callbackType.FullName}'.\");");
        w.CloseBlock();
        w.Line();

        w.OpenBlock("private static Type ResolveImplementationType(Type serviceType)");
        w.Line("var implementations = typeof(AllServicesBinder).Assembly.GetTypes()");
        w.Line("    .Where(type => !type.IsAbstract && !type.IsInterface && !type.IsNested && serviceType.IsAssignableFrom(type))");
        w.Line("    .ToArray();");
        w.OpenBlock("if (implementations.Length == 1)");
        w.Line("return implementations[0];");
        w.CloseBlock();
        w.OpenBlock("if (implementations.Length == 0)");
        w.Line("throw new InvalidOperationException($\"No service implementation found for '{serviceType.FullName}' in assembly '{typeof(AllServicesBinder).Assembly.GetName().Name}'.\");");
        w.CloseBlock();
        w.Line("var names = string.Join(\", \", implementations.Select(static type => type.FullName));");
        w.Line("throw new InvalidOperationException($\"Multiple service implementations found for '{serviceType.FullName}': {names}. Use the individual generated binders when you need explicit service instances or factories instead.\");");
        w.CloseBlock();
    }
}
