using ULinkRPC.CodeGen;
using Xunit;

namespace ULinkRPC.CodeGen.Tests;

public class ClientEmitterTests
{
    private static RpcServiceInfo MakeService(params RpcMethodInfo[] methods) =>
        new("IPlayerService", "MyGame.Contracts.IPlayerService", 1, [.. methods], ["MyGame.Contracts"]);

    private static RpcMethodInfo VoidMethod(string name, int id, params RpcParameterInfo[] parameters) =>
        new(name, id, [.. parameters], null, true);

    private static RpcMethodInfo ReturnMethod(string name, int id, string retType, params RpcParameterInfo[] parameters) =>
        new(name, id, [.. parameters], retType, false);

    private static RpcParameterInfo Param(string type, string name) => new(type, name);

    #region Auto-generated header

    [Fact]
    public void GeneratedCode_HasAutoGeneratedHeader()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.StartsWith("// <auto-generated/>", code);
        Assert.Contains("#pragma warning disable", code);
    }

    [Fact]
    public void CallbackBinder_HasAutoGeneratedHeader()
    {
        var svc = MakeServiceWithCallback();
        var code = ClientEmitter.GenerateCallbackBinder(svc, "Gen", "ULinkRPC.Core");

        Assert.StartsWith("// <auto-generated/>", code);
    }

    #endregion

    #region Client class structure

    [Fact]
    public void GeneratesClientClass_WithServiceIdAndConstructor()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("public sealed class PlayerServiceClient : IPlayerService", code);
        Assert.Contains("private const int ServiceId = 1;", code);
        Assert.Contains("private readonly IRpcClient _client;", code);
        Assert.Contains("public PlayerServiceClient(IRpcClient client) { _client = client; }", code);
    }

    [Fact]
    public void GeneratesExtensionMethod()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("public static class PlayerServiceClientExtensions", code);
        Assert.Contains("public static IPlayerService CreatePlayerService(this IRpcClient client)", code);
        Assert.Contains("throw new ArgumentNullException(nameof(client))", code);
        Assert.Contains("return new PlayerServiceClient(client);", code);
    }

    [Fact]
    public void GeneratesUsingsAndNamespace()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "My.Generated", "ULinkRPC.Core");

        Assert.Contains("using System;", code);
        Assert.Contains("using System.Threading;", code);
        Assert.Contains("using System.Threading.Tasks;", code);
        Assert.Contains("using ULinkRPC.Core;", code);
        Assert.Contains("namespace My.Generated", code);
    }

    [Fact]
    public void ExcludesCoreRuntimeFromContractUsings()
    {
        var svc = new RpcServiceInfo("IFoo", "Ns.IFoo", 1,
            [VoidMethod("Do", 1, Param("DoRequest", "request"))], ["ULinkRPC.Core", "Ns"]);
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        var coreOccurrences = code.Split("using ULinkRPC.Core;").Length - 1;
        Assert.Equal(1, coreOccurrences);
    }

    #endregion

    #region Methods

    [Fact]
    public void VoidMethod_UsesSingleRequestDto()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("private static readonly RpcMethod<PingRequest, RpcVoid> pingRpcMethod = new(ServiceId, 1);", code);
        Assert.Contains("public async ValueTask Ping(PingRequest request)", code);
        Assert.Contains("public async ValueTask Ping(PingRequest request, CancellationToken ct)", code);
        Assert.Contains("await _client.CallAsync(pingRpcMethod, request, ct);", code);
    }

    [Fact]
    public void VoidMethod_OneDtoParam()
    {
        var svc = MakeService(VoidMethod("SetName", 2, Param("SetNameRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("private static readonly RpcMethod<SetNameRequest, RpcVoid> setNameRpcMethod", code);
        Assert.Contains("public async ValueTask SetName(SetNameRequest request)", code);
        Assert.Contains("public async ValueTask SetName(SetNameRequest request, CancellationToken ct)", code);
        Assert.Contains("await _client.CallAsync(setNameRpcMethod, request, ct);", code);
    }

    #endregion

    #region Non-void methods

    [Fact]
    public void NonVoidMethod_UsesSingleRequestDto()
    {
        var svc = MakeService(ReturnMethod("GetCount", 1, "GetCountReply", Param("GetCountRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("private static readonly RpcMethod<GetCountRequest, GetCountReply> getCountRpcMethod", code);
        Assert.Contains("public ValueTask<GetCountReply> GetCount(GetCountRequest request)", code);
        Assert.Contains("public ValueTask<GetCountReply> GetCount(GetCountRequest request, CancellationToken ct)", code);
        Assert.Contains("return _client.CallAsync(getCountRpcMethod, request, ct);", code);
    }

    [Fact]
    public void NonVoidMethod_OneDtoParam()
    {
        var svc = MakeService(ReturnMethod("GetName", 1, "GetNameReply", Param("GetNameRequest", "request")));
        var code = ClientEmitter.GenerateClient(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("RpcMethod<GetNameRequest, GetNameReply>", code);
        Assert.Contains("public ValueTask<GetNameReply> GetName(GetNameRequest request)", code);
        Assert.Contains("return _client.CallAsync(getNameRpcMethod, request, ct);", code);
    }

    #endregion

    #region Callback binder

    [Fact]
    public void CallbackBinder_GeneratesStructure()
    {
        var svc = MakeServiceWithCallback();
        var code = ClientEmitter.GenerateCallbackBinder(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("public static class GameCallbackBinder", code);
        Assert.Contains("private const int ServiceId = 1;", code);
        Assert.Contains("public static void Bind(IRpcClient client, IGameCallback receiver)", code);
    }

    [Fact]
    public void CallbackBinder_OneDto_DispatchesDirectly()
    {
        var svc = MakeServiceWithCallback(new RpcCallbackMethodInfo("OnPing", 1, [Param("PingNotify", "notify")]));
        var code = ClientEmitter.GenerateCallbackBinder(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("RpcPushMethod<PingNotify>", code);
        Assert.Contains("receiver.OnPing(arg);", code);
    }

    [Fact]
    public void CallbackBinder_OneParam_PassesDtoDirectly()
    {
        var svc = MakeServiceWithCallback(
            new RpcCallbackMethodInfo("OnEvent", 1, [Param("EventNotify", "notify")]));
        var code = ClientEmitter.GenerateCallbackBinder(svc, "Gen", "ULinkRPC.Core");

        Assert.Contains("RpcPushMethod<EventNotify>", code);
        Assert.Contains("receiver.OnEvent(arg);", code);
    }

    private static RpcServiceInfo MakeServiceWithCallback(params RpcCallbackMethodInfo[] cbMethods)
    {
        var svc = new RpcServiceInfo("IGameService", "Ns.IGameService", 1,
            [VoidMethod("Start", 1, Param("StartRequest", "request"))], ["Ns"])
        {
            CallbackInterfaceName = "IGameCallback",
            CallbackInterfaceFullName = "Ns.IGameCallback"
        };
        svc.CallbackMethods = cbMethods.Length > 0 ? [.. cbMethods]
            : [new RpcCallbackMethodInfo("OnEvent", 1, [Param("EventNotify", "notify")])];
        return svc;
    }

    #endregion
}
