using ULinkRPC.CodeGen;
using Xunit;

namespace ULinkRPC.CodeGen.Tests;

public class ServerEmitterTests
{
    private static RpcServiceInfo MakeService(params RpcMethodInfo[] methods) =>
        new("IPlayerService", "MyGame.Contracts.IPlayerService", 1, [.. methods], ["MyGame.Contracts"]);

    private static RpcMethodInfo VoidMethod(string name, int id, params RpcParameterInfo[] parameters) =>
        new(name, id, [.. parameters], null, true);

    private static RpcMethodInfo ReturnMethod(string name, int id, string retType, params RpcParameterInfo[] parameters) =>
        new(name, id, [.. parameters], retType, false);

    private static RpcParameterInfo Param(string type, string name) => new(type, name);

    #region Auto-generated header

    [Fact]
    public void Binder_HasAutoGeneratedHeader()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");
        Assert.StartsWith("// <auto-generated/>", code);
    }

    [Fact]
    public void CallbackProxy_HasAutoGeneratedHeader()
    {
        var svc = MakeServiceWithCallback();
        var code = ServerEmitter.GenerateCallbackProxy(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");
        Assert.StartsWith("// <auto-generated/>", code);
    }

    [Fact]
    public void AllServicesBinder_HasAutoGeneratedHeader()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateAllServicesBinder([svc], "S", "ULinkRPC.Server");
        Assert.StartsWith("// <auto-generated/>", code);
    }

    #endregion

    #region Binder structure

    [Fact]
    public void Binder_GeneratesClassAndBindMethod()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("public static class PlayerServiceBinder", code);
        Assert.Contains("private const int ServiceId = 1;", code);
        Assert.Contains("public static void Bind(RpcServiceRegistry registry, IPlayerService impl)", code);
    }

    [Fact]
    public void Binder_GeneratesUsings()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("using System;", code);
        Assert.Contains("using System.Threading.Tasks;", code);
        Assert.Contains("using ULinkRPC.Core;", code);
        Assert.Contains("using ULinkRPC.Server;", code);
    }

    #endregion

    #region Binder - deserialization patterns

    [Fact]
    public void Binder_OneRequestDto_DeserializesToSingleArg()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("registry.Register(ServiceId, 1,", code);
        Assert.Contains("var impl = server.GetOrAddScopedService(ServiceId, implFactory);", code);
        Assert.Contains("var arg = server.Serializer.Deserialize<PingRequest>(req.Payload)!;", code);
        Assert.Contains("await impl.Ping(arg)", code);
    }

    [Fact]
    public void Binder_OneParam_DeserializesToVariable()
    {
        var svc = MakeService(VoidMethod("Set", 1, Param("SetRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("var arg = server.Serializer.Deserialize<SetRequest>(req.Payload)!;", code);
        Assert.Contains("await impl.Set(arg)", code);
    }

    #endregion

    #region Binder - void vs non-void response

    [Fact]
    public void Binder_VoidMethod_ReturnsEmptyPayload()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("Payload = Array.Empty<byte>()", code);
    }

    [Fact]
    public void Binder_NonVoidMethod_SerializesResponse()
    {
        var svc = MakeService(ReturnMethod("Get", 1, "GetReply", Param("GetRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("var resp = await impl.Get(arg)", code);
        Assert.Contains("Payload = server.Serializer.Serialize(resp)", code);
    }

    #endregion

    #region Delegate bind overload

    [Fact]
    public void DelegateOverload_GeneratesDelegateImplClass()
    {
        var svc = MakeService(
            VoidMethod("Ping", 1, Param("PingRequest", "request")),
            ReturnMethod("Get", 2, "GetReply", Param("GetRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("private sealed class DelegateImpl : IPlayerService", code);
        Assert.Contains("Func<PingRequest, ValueTask> pingHandler", code);
        Assert.Contains("Func<GetRequest, ValueTask<GetReply>> getHandler", code);
        Assert.Contains("_pingHandler = pingHandler ?? throw new ArgumentNullException", code);
    }

    [Fact]
    public void DelegateOverload_WithParams_CorrectSignature()
    {
        var svc = MakeService(VoidMethod("Set", 1, Param("SetRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("Func<SetRequest, ValueTask> setHandler", code);
    }

    #endregion

    #region Callback factory bind

    [Fact]
    public void CallbackFactoryBind_GeneratesOverload()
    {
        var svc = MakeServiceWithCallback();
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("public static void Bind(RpcServiceRegistry registry, Func<IGameCallback, IGameSvc> implFactory)", code);
        Assert.Contains("BindFactory(registry, session => implFactory(new GameCallbackProxy(session))", code);
    }

    [Fact]
    public void NoCallback_NoFactoryOverload()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateBinder(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.DoesNotContain("Func<IGameCallback, IGameSvc>", code);
    }

    #endregion

    #region Callback proxy

    [Fact]
    public void CallbackProxy_UsesFireAndForget_NotWait()
    {
        var svc = MakeServiceWithCallback(
            new RpcCallbackMethodInfo("OnEvent", 1, [Param("EventNotify", "notify")]));
        var code = ServerEmitter.GenerateCallbackProxy(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("public sealed class GameCallbackProxy : IGameCallback", code);
        Assert.Contains("_ = _session.PushAsync<EventNotify>(ServiceId, 1, notify).AsTask();", code);
        Assert.DoesNotContain(".Wait()", code);
    }

    [Fact]
    public void CallbackProxy_OneDtoPayload()
    {
        var svc = MakeServiceWithCallback(new RpcCallbackMethodInfo("OnPing", 1, [Param("PingNotify", "notify")]));
        var code = ServerEmitter.GenerateCallbackProxy(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("_ = _session.PushAsync<PingNotify>(ServiceId, 1, notify).AsTask();", code);
    }

    [Fact]
    public void CallbackProxy_MultipleCallbackMethods()
    {
        var svc = MakeServiceWithCallback(
            new RpcCallbackMethodInfo("OnA", 1, [Param("int", "a")]),
            new RpcCallbackMethodInfo("OnB", 2, [Param("string", "b")]));
        var code = ServerEmitter.GenerateCallbackProxy(svc, "S", "ULinkRPC.Core", "ULinkRPC.Server");

        Assert.Contains("public void OnA(int a)", code);
        Assert.Contains("public void OnB(string b)", code);
    }

    #endregion

    #region AllServicesBinder

    [Fact]
    public void AllServicesBinder_SingleService()
    {
        var svc = MakeService(VoidMethod("Ping", 1, Param("PingRequest", "request")));
        var code = ServerEmitter.GenerateAllServicesBinder([svc], "S", "ULinkRPC.Server");

        Assert.Contains("[assembly: RpcGeneratedServicesBinder(typeof(S.AllServicesBinder))]", code);
        Assert.Contains("public static class AllServicesBinder", code);
        Assert.Contains("public static void BindAll(RpcServiceRegistry registry)", code);
        Assert.Contains("PlayerServiceBinder.BindFactory(registry, CreateServiceFactory<IPlayerService>());", code);
        Assert.Contains("public static void BindAll(RpcServiceRegistry registry, IPlayerService playerService)", code);
        Assert.Contains("PlayerServiceBinder.Bind(registry, playerService);", code);
    }

    [Fact]
    public void AllServicesBinder_MultipleServices()
    {
        var svc1 = MakeService(VoidMethod("Do", 1, Param("DoRequest", "request")));
        var svc2 = new RpcServiceInfo("IChatService", "Ns.IChatService", 2,
            [VoidMethod("Send", 1, Param("SendRequest", "request"))], ["Ns"]);
        var code = ServerEmitter.GenerateAllServicesBinder([svc1, svc2], "S", "ULinkRPC.Server");

        Assert.Contains("IPlayerService playerService", code);
        Assert.Contains("IChatService chatService", code);
        Assert.Contains("PlayerServiceBinder.BindFactory(registry, CreateServiceFactory<IPlayerService>());", code);
        Assert.Contains("ChatServiceBinder.BindFactory(registry, CreateServiceFactory<IChatService>());", code);
        Assert.Contains("PlayerServiceBinder.Bind(registry, playerService);", code);
        Assert.Contains("ChatServiceBinder.Bind(registry, chatService);", code);
    }

    [Fact]
    public void AllServicesBinder_CallbackService_GeneratesAutomaticAndExplicitFactoryBinding()
    {
        var svc = MakeServiceWithCallback();
        var code = ServerEmitter.GenerateAllServicesBinder([svc], "S", "ULinkRPC.Server");

        Assert.Contains("using System;", code);
        Assert.Contains("public static void BindAll(RpcServiceRegistry registry)", code);
        Assert.Contains("GameSvcBinder.Bind(registry, CreateCallbackServiceFactory<IGameSvc, IGameCallback>());", code);
        Assert.Contains("public static void BindAll(RpcServiceRegistry registry, Func<IGameCallback, IGameSvc> gameSvcFactory)", code);
        Assert.Contains("GameSvcBinder.Bind(registry, gameSvcFactory);", code);
    }

    [Fact]
    public void AllServicesBinder_AutoDiscovery_IgnoresNestedImplementationTypes()
    {
        var svc = MakeServiceWithCallback();
        var code = ServerEmitter.GenerateAllServicesBinder([svc], "S", "ULinkRPC.Server");

        Assert.Contains("!type.IsNested", code);
    }

    #endregion

    private static RpcServiceInfo MakeServiceWithCallback(params RpcCallbackMethodInfo[] cbMethods)
    {
        var svc = new RpcServiceInfo("IGameSvc", "Ns.IGameSvc", 1,
            [VoidMethod("Start", 1, Param("StartRequest", "request"))], ["Ns"])
        {
            CallbackInterfaceName = "IGameCallback",
            CallbackInterfaceFullName = "Ns.IGameCallback"
        };
        svc.CallbackMethods = cbMethods.Length > 0 ? [.. cbMethods]
            : [new RpcCallbackMethodInfo("OnEvent", 1, [Param("EventNotify", "notify")])];
        return svc;
    }
}
