// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Game.Rpc.Contracts;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class InventoryServiceClient : IInventoryService
    {
        private const int ServiceId = 2;
        private static readonly RpcMethod<RevisionRequest, RevisionReply> getRevisionAsyncRpcMethod = new(ServiceId, 1);
        private static readonly RpcMethod<RevisionRequest, RevisionReply> incrRevisionRpcMethod = new(ServiceId, 2);

        private readonly IRpcClient _client;

        public InventoryServiceClient(IRpcClient client) { _client = client; }

        public ValueTask<RevisionReply> GetRevisionAsync(RevisionRequest req)
        {
            return GetRevisionAsync(req, CancellationToken.None);
        }

        public ValueTask<RevisionReply> GetRevisionAsync(RevisionRequest req, CancellationToken ct)
        {
            return _client.CallAsync(getRevisionAsyncRpcMethod, req, ct);
        }

        public ValueTask<RevisionReply> IncrRevision(RevisionRequest req)
        {
            return IncrRevision(req, CancellationToken.None);
        }

        public ValueTask<RevisionReply> IncrRevision(RevisionRequest req, CancellationToken ct)
        {
            return _client.CallAsync(incrRevisionRpcMethod, req, ct);
        }

    }

    public static class InventoryServiceClientExtensions
    {
        public static IInventoryService CreateInventoryService(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new InventoryServiceClient(client);
        }
    }
}
