// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using Game.Rpc.Contracts;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public static class InventoryCallbackBinder
    {
        private const int ServiceId = 2;

        private static readonly RpcPushMethod<string> onInventoryNotifyPushMethod = new(ServiceId, 1);

        public static void Bind(IRpcClient client, IInventoryCallback receiver)
        {
            client.RegisterPushHandler(onInventoryNotifyPushMethod, (arg) =>
            {
                receiver.OnInventoryNotify(arg);
            });

        }
    }
}
