// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Game.Rpc.Contracts;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class InventoryServiceClient : IInventoryService
    {
        private const int ServiceId = 2;
        private static readonly RpcMethod<RpcVoid, int> getRevisionAsyncRpcMethod = new(ServiceId, 1);
        private static readonly RpcMethod<RpcVoid, int> incrRevisionRpcMethod = new(ServiceId, 2);

        private readonly IRpcClient _client;

        public InventoryServiceClient(IRpcClient client) { _client = client; }

        public ValueTask<int> GetRevisionAsync()
        {
            return GetRevisionAsync(CancellationToken.None);
        }

        public ValueTask<int> GetRevisionAsync(CancellationToken ct)
        {
            return _client.CallAsync(getRevisionAsyncRpcMethod, default, ct);
        }

        public ValueTask<int> IncrRevision()
        {
            return IncrRevision(CancellationToken.None);
        }

        public ValueTask<int> IncrRevision(CancellationToken ct)
        {
            return _client.CallAsync(incrRevisionRpcMethod, default, ct);
        }

    }

    public static class InventoryServiceClientExtensions
    {
        public static IInventoryService CreateInventoryService(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new InventoryServiceClient(client);
        }
    }
}
