// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Game.Rpc.Contracts;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class QuestServiceClient : IQuestService
    {
        private const int ServiceId = 3;
        private static readonly RpcMethod<RpcVoid, int> getProgressAsyncRpcMethod = new(ServiceId, 1);
        private static readonly RpcMethod<RpcVoid, int> incrProgressRpcMethod = new(ServiceId, 2);

        private readonly IRpcClient _client;

        public QuestServiceClient(IRpcClient client) { _client = client; }

        public ValueTask<int> GetProgressAsync()
        {
            return GetProgressAsync(CancellationToken.None);
        }

        public ValueTask<int> GetProgressAsync(CancellationToken ct)
        {
            return _client.CallAsync(getProgressAsyncRpcMethod, default, ct);
        }

        public ValueTask<int> IncrProgress()
        {
            return IncrProgress(CancellationToken.None);
        }

        public ValueTask<int> IncrProgress(CancellationToken ct)
        {
            return _client.CallAsync(incrProgressRpcMethod, default, ct);
        }

    }

    public static class QuestServiceClientExtensions
    {
        public static IQuestService CreateQuestService(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new QuestServiceClient(client);
        }
    }
}
