// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using Game.Rpc.Contracts;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class RpcApi
    {
        public RpcApi(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Game = new GameRpcGroup(client);
        }

        public GameRpcGroup Game { get; }
    }

    public sealed class GameRpcGroup
    {
        public GameRpcGroup(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Player = client.CreatePlayerService();
        }

        public IPlayerService Player { get; }
    }

    public static class RpcApiExtensions
    {
        public static RpcApi CreateRpcApi(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new RpcApi(client);
        }
    }
}
