baseURL = "https://bruce48x.github.io/ULinkRPC/"
languageCode = "zh-cn"
title = "ULinkRPC Docs"

[params]
description = "Documentation site for ULinkRPC."
repo = "https://github.com/bruce48x/ULinkRPC"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
