// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using Game.Rpc.Contracts;
using ULinkRPC.Client;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class RpcApi
    {
        public RpcApi(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Game = new GameRpcGroup(client);
        }

        public GameRpcGroup Game { get; }
    }

    public sealed class GameRpcGroup
    {
        public GameRpcGroup(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Player = client.CreatePlayerService();
        }

        public IPlayerService Player { get; }
    }

    public sealed class RpcConnection : IAsyncDisposable
    {
        public RpcConnection(RpcClient client)
        {
            Client = client ?? throw new ArgumentNullException(nameof(client));
            Api = new RpcApi(client);
        }

        public RpcApi Api { get; }
        public RpcClient Client { get; }

        public static ValueTask<RpcConnection> ConnectAsync(RpcClientBuilder builder, CancellationToken ct = default)
        {
            if (builder is null) throw new ArgumentNullException(nameof(builder));
            return builder.ConnectTypedAsync(static client => new RpcConnection(client), configureClient: null, ct);
        }

        public static ValueTask<RpcConnection> ConnectAsync(RpcClientBuilder builder, RpcCallbackBindings callbacks, CancellationToken ct = default)
        {
            if (builder is null) throw new ArgumentNullException(nameof(builder));
            if (callbacks is null) throw new ArgumentNullException(nameof(callbacks));
            return builder.ConnectTypedAsync(static client => new RpcConnection(client), callbacks.Bind, ct);
        }

        public sealed class RpcCallbackBindings : IEnumerable<object>
        {
            private IPlayerCallback? _playerCallback;
            public void Add(IPlayerCallback playerCallback)
            {
                if (playerCallback is null) throw new ArgumentNullException(nameof(playerCallback));
                if (_playerCallback is not null)
                {
                    throw new InvalidOperationException("Callback receiver for 'IPlayerCallback' is already registered.");
                }
                _playerCallback = playerCallback;
            }

            internal void Bind(IRpcClient client)
            {
                if (client is null) throw new ArgumentNullException(nameof(client));
                if (_playerCallback is not null)
                {
                    PlayerCallbackBinder.Bind(client, _playerCallback);
                }
            }

            public IEnumerator<object> GetEnumerator()
            {
                yield break;
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                return GetEnumerator();
            }

        }

        public abstract class PlayerCallbackBase : IPlayerCallback
        {

            public virtual void OnNotify(string message)
            {
            }
        }

        public ValueTask DisposeAsync()
        {
            return Client.DisposeAsync();
        }
    }

    public static class RpcApiExtensions
    {
        public static RpcApi CreateRpcApi(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new RpcApi(client);
        }
    }

    public sealed class GameRpcClient : IAsyncDisposable
    {
        private GameRpcClient(RpcConnection connection)
        {
            Connection = connection ?? throw new ArgumentNullException(nameof(connection));
        }

        public RpcConnection Connection { get; }
        public RpcApi Api => Connection.Api;
        public RpcClient Client => Connection.Client;
        public GameRpcGroup Game => Api.Game;

        public static async ValueTask<GameRpcClient> ConnectAsync(RpcClientBuilder builder, CancellationToken ct = default)
        {
            var connection = await RpcConnection.ConnectAsync(builder, ct);
            return new GameRpcClient(connection);
        }

        public static async ValueTask<GameRpcClient> ConnectAsync(RpcClientBuilder builder, RpcConnection.RpcCallbackBindings callbacks, CancellationToken ct = default)
        {
            var connection = await RpcConnection.ConnectAsync(builder, callbacks, ct);
            return new GameRpcClient(connection);
        }

        public ValueTask DisposeAsync()
        {
            return Connection.DisposeAsync();
        }
    }
}
