// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Game.Rpc.Contracts;
using ULinkRPC.Client;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class RpcApi
    {
        public RpcApi(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Game = new GameRpcGroup(client);
        }

        public GameRpcGroup Game { get; }
    }

    public sealed class GameRpcGroup
    {
        public GameRpcGroup(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Player = client.CreatePlayerService();
        }

        public IPlayerService Player { get; }
    }

}

namespace ULinkRPC.Client
{
    public sealed class RpcClient : IAsyncDisposable
    {
        private readonly RpcClientRuntime _runtime;
        private readonly RpcCallbackBindings? _callbacks;
        private global::Rpc.Generated.RpcApi? _api;

        public RpcClient(RpcClientOptions options)
        {
            Options = options ?? throw new ArgumentNullException(nameof(options));
            _runtime = new RpcClientRuntime(options.Transport, options.Serializer);
        }

        public RpcClient(RpcClientOptions options, RpcCallbackBindings callbacks) : this(options)
        {
            _callbacks = callbacks ?? throw new ArgumentNullException(nameof(callbacks));
        }

        public sealed class RpcCallbackBindings
        {
            private IPlayerCallback? _playerCallback;
            public void Add(IPlayerCallback playerCallback)
            {
                if (playerCallback is null) throw new ArgumentNullException(nameof(playerCallback));
                if (_playerCallback is not null)
                {
                    throw new InvalidOperationException("Callback receiver for 'IPlayerCallback' is already registered.");
                }
                _playerCallback = playerCallback;
            }

            internal void Bind(IRpcClient client)
            {
                if (client is null) throw new ArgumentNullException(nameof(client));
                if (_playerCallback is not null)
                {
                    PlayerCallbackBinder.Bind(client, _playerCallback);
                }
            }
        }

        public abstract class PlayerCallbackBase : IPlayerCallback
        {

            public virtual void OnNotify(string message)
            {
            }
        }

        public event Action<Exception?>? Disconnected
        {
            add => _runtime.Disconnected += value;
            remove => _runtime.Disconnected -= value;
        }

        public RpcClientOptions Options { get; }
        public global::Rpc.Generated.RpcApi Api => _api ??= new global::Rpc.Generated.RpcApi(_runtime);

        public ValueTask ConnectAsync(CancellationToken ct = default)
        {
            if (_callbacks is not null)
                _callbacks.Bind(_runtime);
            return _runtime.StartAsync(ct);
        }

        public ValueTask DisposeAsync()
        {
            return _runtime.DisposeAsync();
        }
    }
}
