// <auto-generated/>
// This file was auto-generated by ULinkRPC.CodeGen. Do not edit.
#pragma warning disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Game.Rpc.Contracts;
using ULinkRPC.Client;
using ULinkRPC.Core;

namespace Rpc.Generated
{
    public sealed class RpcApi
    {
        public RpcApi(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Game = new GameRpcGroup(client);
        }

        public GameRpcGroup Game { get; }
    }

    public sealed class GameRpcGroup
    {
        public GameRpcGroup(IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            Player = client.CreatePlayerService();
        }

        public IPlayerService Player { get; }
    }

    public sealed class RpcConnection : IAsyncDisposable
    {
        public RpcConnection(RpcClient client)
        {
            Client = client ?? throw new ArgumentNullException(nameof(client));
            Api = new RpcApi(client);
        }

        public RpcApi Api { get; }
        public RpcClient Client { get; }

        public static ValueTask<RpcConnection> ConnectAsync(RpcClientBuilder builder, IPlayerCallback? playerCallback = null, CancellationToken ct = default)
        {
            if (builder is null) throw new ArgumentNullException(nameof(builder));
            return builder.ConnectTypedAsync(static client => new RpcConnection(client), client => BindCallbacks(client, playerCallback), ct);
        }

        private static void BindCallbacks(IRpcClient client, IPlayerCallback? playerCallback)
        {
            if (playerCallback is not null)
            {
                PlayerCallbackBinder.Bind(client, playerCallback);
            }
        }

        public ValueTask DisposeAsync()
        {
            return Client.DisposeAsync();
        }
    }

    public static class RpcApiExtensions
    {
        public static RpcApi CreateRpcApi(this IRpcClient client)
        {
            if (client is null) throw new ArgumentNullException(nameof(client));
            return new RpcApi(client);
        }
    }
}
